default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: daily_smarty_development

test:
  <<: *default
  database: daily_smarty_test

production:
  <<: *default
  database: daily_smarty_production
  username: daily_smarty
  password: <%= ENV['DAILY_SMARTY_DATABASE_PASSWORD'] %>
